big update to deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,8 +1,37 @@
 #!/bin/bash
+# Distinct deployment servers
+# - gpu
+# - cal-im
+# - cr
+# Distinct environments
+# - deployment -- reliable, tested
+# - development -- testing
 
-# Installs contents of this repo.
-LOG=~/deploy_dsa110-pyutils.log
-DATE="`date --iso-8601='seconds'`"
-echo "$DATE: `which python`" > $LOG
-output=`pip install .`
-echo "$DATE: $output" >> $LOG
+# setup
+NAME="dsa110-pyutils"
+DATE=$(date --iso-8601=seconds)
+LOG=~/deploy_${NAME}_${DATE}.log
+
+set -ex >> $LOG 2>>$LOG
+
+rm ~/deploy_$NAME_*.log >> $LOG 2>>$LOG  # clean up old logs
+echo $HOSTNAME >> $LOG 2>>$LOG  # should be installing on calim
+echo $PWD >> $LOG 2>>$LOG  # should be base of code repo
+whoami >> $LOG 2>>$LOG  # should be user pipeline (or ubuntu?)
+
+if [[ $PWD =~ $NAME ]]; then
+    if [[ $HOSTNAME =~ 'calim' ]]; then
+	echo "$DATE" >> $LOG 2>>$LOG
+	conda run -n deployment which python >> $LOG 2>>$LOG
+	if [[ $? == 0 ]]; then
+	    conda run -n deployment git describe >> $LOG 2>>$LOG
+	fi    
+	if [[ $? == 0 ]]; then
+	    conda run -n deployment pip install . >> $LOG 2>>$LOG
+	fi
+    else
+	echo "Not installing on this host" >> $LOG 2>>$LOG
+    fi
+else
+    echo "Not installing in this location" >> $LOG 2>>$LOG
+fi
